- name: 'chore'
  color: 'bfd4f2'
- name: 'ci'
  color: '491043'
- name: 'bug'
  color: 'd73a4a'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'feat'
  color: 'FBCA04'
- name: 'fix'
  color: 'B99F0C'
- name: 'good first issue'
  color: '7057ff'
- name: 'help wanted'
  color: '008672'
- name: 'Improvements'
  color: '0075ca'
- name: 'invalid'
  color: 'e4e669'
- name: 'question'
  color: 'd876e3'
- name: 'refactor'
  color: '0FF5D6'
- name: 'wontfix'
  color: 'ffffff'